### ISSUE TITLE
After most recent update, all scrapers throwing exception for refresh interval

### ISSUE THREAD

**Issue by bgsmith17** [EricJMarti/inventory-hunter#180] opened 2021-03-22 13:45 UTC
caught exception during request: 15.0 has type float, but expected one of: int, long

In the .yaml I have entered 15, no decimal place, but somewhere in the code it is getting cast to a float and now none of the scrapers work.  Anyone got a fix?
edit: on windows docker
edit2: also on my raspberry pi 4

**Comment by EricJMarti** [comment] 2021-03-22 22:31
@bgsmith17  I am unable to reproduce this locally so I'm curious what your yaml file looks like.

Just to be safe, I committed what I think is a fix: https://github.com/EricJMarti/inventory-hunter/commit/47495544927b376b298d181f97a901b2c7b8fbcd

**Comment by bgsmith17** [comment] 2021-03-22 22:38
Thanks for the quick response.  Attached are the YAMLs I've been working with (converted to .txt format).
[amazon_rtx_3080.txt](https://github.com/EricJMarti/inventory-hunter/files/6185693/amazon_rtx_3080.txt)
[newegg_rtx_3080.txt](https://github.com/EricJMarti/inventory-hunter/files/6185695/newegg_rtx_3080.txt)
[ps5.txt](https://github.com/EricJMarti/inventory-hunter/files/6185696/ps5.txt)

I'll update and let you know how it goes when I get home.

**Comment by bgsmith17** [comment] 2021-03-23 02:52
It appears that it was my .yaml files after all, after reinstalling and updating the packaged ones rather than the ones I had made from scratch the scrapers appear to be working.  I'll let it run over night before closing the issue, but I think we're good.

**Closed** 2021-03-23 17:11 UTC
