### ISSUE TITLE
newegg caught exception 

### ISSUE THREAD

**Issue by sohailoo** [EricJMarti/inventory-hunter#71] opened 2020-12-05 11:13 UTC
```
W2020-12-05 11:06:52,016 [nwgg_2] missing buy box: https://www.newegg.com/areyouahuman?referer=/areyouahuman?referer=https%3A%2F%2Fwww.newegg.com%2FProduct%2FComboDealDetails%3FItemList%3DCombo.4190361&why=8
E2020-12-05 11:06:52,017 [nwgg_2] got "are you a human" prompt
E2020-12-05 11:06:52,017 [root] caught exception
Traceback (most recent call last):
  File "/src/run.py", line 45, in main
    hunt(args, config, scrapers)
  File "/src/hunter.py", line 103, in hunt
    engine.run()
  File "/src/hunter.py", line 27, in run
    self.scheduler.run(blocking=True)
  File "/usr/local/lib/python3.9/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/src/hunter.py", line 42, in tick
    self.process_scrape_result(s, result)
  File "/src/hunter.py", line 89, in process_scrape_result
    self.alerter('Something went wrong',
TypeError: __call__() takes 2 positional arguments but 3 were given

```

**Comment by EricJMarti** [comment] 2020-12-05 17:28
This is caused by Newegg's anti-scraping logic. The only fix for this is to increase your refresh interval.

**Closed by EricJMarti** 2020-12-05 17:28 UTC
