### ISSUE TITLE
[QUESTION] Issues getting this to work.

### ISSUE THREAD

**Issue by joshuagascan** [EricJMarti/inventory-hunter#6] opened 2020-11-25 19:07 UTC
I want to preface this by saying I am very new to working with raspberrypis. I set up the email system on the same pi as the inventory-hunter and have verified that the emails are working. Everything seems to be working fine and based on another question you answered I set the relay as the pi's local ip address 10.0.0.131. I am assuming the email is the one I want the notifications set to and I specified the config file as "bhphoto_rtx_3070.yaml". Every time I try to run the docket_run.bash command it says that the config file does not exist or is not a regular file. If you can help me I would really appreciate it. This was another cool project to try on my PI4 and help a friend get his hands on the almighty 3070.

**Comment by EricJMarti** [comment] 2020-11-25 19:18
That error occurs if the `docker_run.bash` script can't find the config file you're referring to. The script expects a relative/absolute file path for the config file argument. For example:
```
$ ./docker_run.bash -c ./config/bhphoto_rtx_3070.yaml -e <email_address> -r <relay_ip_address>
```

**Comment by joshuagascan** [comment] 2020-11-25 19:30
Awesome that worked. Sorry for my ignorance. Do I need to run this for all 3 config files as well now or can I only run one at a time? Can I run the same command again with a different email address as well to notify more than one person?

**Comment by EricJMarti** [comment] 2020-11-25 19:56
I would run the `docker_run.bash` script three times (once per RTX 3070 config), which will start three containers (one per retailer).

Right now, the email address argument to `docker_run.bash` is assumed to be both the sender and recipient email (ie: I'm emailing myself alerts). That said, I think it makes a lot of sense to allow users to set multiple recipient email addresses. I will make that code change and let you know.

**Comment by EricJMarti** [comment] 2020-11-26 00:08
Just committed a code change to allow multiple recipient email addresses to be configured. You can now use the `docker_run.bash` script to specify multiple emails:
```
$ ./docker_run.bash -c <config_file> -r <relay_ip_address> -e <email_address_1> -e <email_address_2> ...
```
The first email address is assumed to be the sender email address (the same one configured for the relay).

**Comment by rayontherun** [comment] 2020-11-27 18:31
What would be the equivalent start command in Windows? I am trying to execute from CMD window but it keeps throwing an invalid argument error while trying to execute within the config folder.
`docker container run -c newegg_rtx_3070.yaml -e ramon.villanueva@gmail.com -r 127.0.0.0 inventory-hunter`
Sorry I am very new to using Docker.

**Comment by EricJMarti** [comment] 2020-11-29 02:23
@rayontherun The docker run command should look something like this on Windows:
```
docker run -d --network host -v C:\path\to\config.yaml:/config.yaml inventory-hunter --email myemail@email.com --relay 127.0.0.1
```
I haven't yet tested inventory-hunter on Windows, so it's possible you may run into some issues. I intend to commit a powershell version of `docker_run.bash` once I get a chance to test the project on Windows.

**Comment by bruttal361** [comment] 2020-12-03 02:38
I'm having issues getting it to run. Would really appreciate some feedback.

I found the container but I'm getting this error "run.py: error: argument -c/--config: can't open '/config.yaml': [Errno 2] No such file or directory: '/config.yaml'"

I'm assuming I'm typing the config file path incorrectly, but I'm not sure how to correct it. I'm using Docker Desktop on Windows 10.

**Comment by bruttal361** [comment] 2020-12-03 02:52
I'm using Windows Powershell and this is the command I'm plugging in. 

> docker run -d --network host -v C:\path\to\config.yaml:/config.yaml inventory-hunter -a discord -w https://discordapp.com/api/webhooks/................

**Comment by EricJMarti** [comment] 2020-12-03 02:55
@bruttal361 I think the issue is that you need to replace `C:\path\to\config.yaml` with the appropriate file path to the config you want to use.

**Comment by bruttal361** [comment] 2020-12-03 02:56
I did, I copied the file path the config file

**Comment by MentalMetalhead** [comment] 2020-12-04 03:28
No matter what I do I can't get docker to get an Image so it can run

**Comment by ulbhudda** [comment] 2020-12-05 17:11
@bruttal361 I think you are facing a similar issue I was, I solved it by telling the full config file path like below in the command

`./docker_run.bash -c ~/bhudda/code/inventory-hunter/config/bestbuy_rtx_3070.yaml -a discord -w https://discord.com/api/webhooks/...`

**Comment by EricJMarti** [comment] 2020-12-06 14:51
See: https://github.com/EricJMarti/inventory-hunter/issues/14#issuecomment-739513439

**Closed by EricJMarti** 2020-12-06 14:51 UTC
